apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp10-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exp10-fullcicd
  template:
    metadata:
      labels:
        app: exp10-fullcicd
    spec:
      containers:
        - name: exp10-container
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: exp10-service
spec:
  type: NodePort
  selector:
    app: exp10-fullcicd
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30090